AWS_region:
  region: 'ap-northeast-1'

AWS_credential:
  aws_access_key_id: 'AKIAI4A32CQF45IYC2JQ'
  aws_secret_key: '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'

AWS_EC2:
  image_id: 'ami-06c43a7df16e8213c'
  instance_type: 't2.micro'
  key_name: 'ec2_temp'
  availability_zone: 'ap-northeast-1a'
  security_group_ids:
    - 'sg-068430e095a23f8e3'
  subnet_id: 'subnet-b90b13f0'
