MONGO:
  host: 'npaws.haohao.in'
  port: 27018
  user: 'np_user'
  password: '2018NP'
  database: 'NP_Project5'

RabbitMQ:
  host: 'npaws.haohao.in'
  port: 5672
  virtual_host: 'np_hw5'
  user: 'np_hw5_user'
  password: 'np_hw5'
  using_ssl: false
