BASE_SOURCE=hw1_0416005_basic.cpp
ADVANCE_SOURCE=hw1_0416005_advance.cpp
compile:
	g++ -g -pthread -Wall $(BASE_SOURCE) -o hw1_0416005.out
	g++ -g -pthread -Wall $(ADVANCE_SOURCE) -o hw1_0416005_advance.out
run:compile
	./hw1_0416005.out
clean:
	rm *.out
